### ISSUE TITLE
Docker image usage

### ISSUE THREAD

**Issue by wpzdm** [Diviyan-Kalainathan/CausalDiscoveryToolbox#13]
Hi Diviyan,

Thank you for your project!

I am not very familiar with Docker, but I think it's worth trying.
I did the following:

```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
divkal/cdt-py3.6    0.4.0               2af9c5c51ac1        2 weeks ago         3.34GB
$ docker run -it --entrypoint /bin/bash 2af9c5c51ac1
root@35b4b45ecfc8:/#
```

But it seems there is no python or conda in the image:
```
root@35b4b45ecfc8:/# python
bash: python: command not found
root@35b4b45ecfc8:/# conda
bash: conda: command not found
```
I believe it must be my fault. Could you please give some pointers?

Best,
Abel

**Comment by Diviyan-Kalainathan** [comment]
Hi Abel, 
Thanks for using this package ! 
I think that only python3 is available, and is not linked to the `python`. Could you try executing the command `python3` and if that still doesn't work please try `/usr/bin/python3`. 

I should install conda this docker image, I guess it would bring less confusion. 

Best regards,
Diviyan

**Comment by wpzdm** [comment]
Thank you! `python3` works!

**Comment by Diviyan-Kalainathan** [comment]
Great ! I shall close this issue, don't hesitate to open it again if an issue arises again.
