### ISSUE TITLE
issue in tutorial

### ISSUE THREAD

**Issue by stylianos-kampakis** [Diviyan-Kalainathan/CausalDiscoveryToolbox#23]
print(nx.adj_matrix(output_graph)).todense() does not work. It requires 

print(nx.adjacency_matrix(output_graph)).todense() 

instead

**Comment by Diviyan-Kalainathan** [comment]
Oh right; thanks for the quick feedback ! 
Best,
Diviyan

**Comment by Diviyan-Kalainathan** [comment]
I will be closing this issue, as it should be solved. Don't hesitate to reopen it if the bug still persists in the latest version.
Best,
Diviyan
