### ISSUE TITLE
Failed to import cdt on a machine without GPU.

### ISSUE THREAD

**Issue by yishilin14** [Diviyan-Kalainathan/CausalDiscoveryToolbox#40]
I am using Windows 7 and I don't have a GPU.

I create a fresh conda environment as follows.
```
conda create --prefix venv python=3.7
conda activate ./venv
# Note that I don't have a GPU. https://pytorch.org/get-started/locally/ 
conda install pytorch torchvision cpuonly -c pytorch
conda install pip
pip install cdt
```

Packages:
- pytorch: 1.2.0
- torchversion: 0.4.0
- cdt: 0.5.8
- ...

Executing `import cdt` failed.
![image](https://user-images.githubusercontent.com/7790907/65428875-be675c80-de47-11e9-84a4-4e50753284fb.png)

The following lines caused the problem. https://github.com/Diviyan-Kalainathan/CausalDiscoveryToolbox/blob/6df55f4ec0800a377cb4688b7eaedb2b1f75f3fe/cdt/utils/Settings.py#L161-L163

My workaround is executing `os.environ["CUDA_VISIBLE_DEVICES"]="[]"` before executing `import cdt`.

**Comment by Diviyan-Kalainathan** [comment]
Thanks for the feedback ; this must be an incompatibility issue between GPUtils and Windows, I'll try to add another safeguard, to avoid workarounds :)

**Comment by Diviyan-Kalainathan** [comment]
It should be done; Please try to update your package and check if the error is still there !

**Comment by yishilin14** [comment]
It works now! Thank you so much! Your package is awesome.
