### ISSUE TITLE
Is Graphviz needed when using R's pcalg?

### ISSUE THREAD

**Issue by ArnoVel** [Diviyan-Kalainathan/CausalDiscoveryToolbox#48]
My question is related to [these explanations](http://bactra.org/weblog/914.html) about the pcalg package in R.
I am currently installing the required packages to run CDT's graph-related ```PC.py```.
As the plotting is done using networkx, I figured Graphviz would not be needed.

Am I guessing correctly?
Is there anything more I should know about these R requirements (say, about the path to the packages or some environment variables..)

Thanks,
A.V

**Comment by Diviyan-Kalainathan** [comment]
Hi, 
I don't know if graphviz are in the requirements of the pcalg package. If not, we don't need it; the installation process of all packages can be quite a hassle. 

The file  `/install-deps/install-dependencies.sh` does includes the installation commands for debian based systems: 
```
#!/bin/bash

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
apt-get -q install r-base -y --allow-unauthenticated
apt-get -q install libssl-dev -y
apt-get -q install libgmp3-dev  -y --allow-unauthenticated
apt-get -q install git -y
apt-get -q install build-essential  -y --allow-unauthenticated
apt-get -q install libv8-3.14-dev  -y --allow-unauthenticated
apt-get -q install libcurl4-openssl-dev -y --allow-unauthenticated
Rscript -e 'install.packages(c("V8","sfsmisc","clue","randomForest","lattice","devtools","MASS"),repos="http://cran.us.r-project.org")'
Rscript -e 'source("http://bioconductor.org/biocLite.R"); biocLite(c("CAM", "SID", "bnlearn", "pcalg", "kpcalg", "D2C"))'
Rscript -e 'library(devtools); install_github("cran/momentchi2"); install_github("Diviyan-Kalainathan/RCIT")'
Rscript -e 'install.packages(c("sparsebn"),repos="http://cran.us.r-project.org")'
```

**Comment by ArnoVel** [comment]
Hi,
Sadly, as I was manually installing the requirements (which you list here: ```c("CAM", "SID", "bnlearn", "pcalg", "kpcalg", "D2C")``` ), the following situation appeared:

![Screenshot from 2019-10-03 01-33-50](https://user-images.githubusercontent.com/48685588/66067464-36d3c900-e57e-11e9-9fc1-eee1731d5564.png)

Mind you, I have R 3.6 because R 3.4.4 did not have ```mvtnorn``` which was needed for another dependency.

Will try with BiocManager (biocLite doesn't work with R>=3.5  I think)

Thanks for the help, will update if I had additional problems

**Comment by Diviyan-Kalainathan** [comment]
D2C is not required at the moment; I planned to add the algorithm, so I added the requirement in advance, but it isn't used at the moment.


So maybe skip D2C. The R requirements are managed independently for each algorithm so no issues there. To run PC, you only need to have pcalg, kpcalg and RCIT: 

from `cdt.causality.graph.PC`:
```python
    def __init__(self, CItest="gaussian", method_indep='corr', alpha=0.01,
                 njobs=None, verbose=None):
        """Init the model and its available arguments."""
        if not (RPackages.pcalg and RPackages.kpcalg and RPackages.RCIT):
```

I should add in the documentation the required R packages for each algorithm.

**Comment by Diviyan-Kalainathan** [comment]
and install RCIT from my fork repo, it contains an adaptation of the author's code to make it work with CDT

**Comment by ArnoVel** [comment]
Back to work, was delighted to find this reply!
This will save me tons of time, thanks a lot :)

**Comment by Diviyan-Kalainathan** [comment]
No problem :) ! I will improve the documentation in the next version

**Comment by Diviyan-Kalainathan** [comment]
It should be done ! I will close this issue, don't hesitate to reopen it if an issue arises.
