### ISSUE TITLE
using other data sets - pandas data frame

### ISSUE THREAD

**Issue by andrewczgithub** [Diviyan-Kalainathan/CausalDiscoveryToolbox#49]
Hi @Diviyan-Kalainathan 

How do we use this package with other data sets.
Do we just create a pandas data frame and use the load_data function?

Many thanks,
Best,
Andrew

**Comment by Diviyan-Kalainathan** [comment]
Hi,
no need, just feed the pandas dataframe to the functions :)

**Comment by andrewczgithub** [comment]
![image](https://user-images.githubusercontent.com/46582583/66285144-05108880-e917-11e9-8916-177c7a737370.png)

**Comment by andrewczgithub** [comment]
does this result mean this is no cause and effect.
Using a very small dataset of 10 values and two variables just to test the algorithms?

Many thanks,
Best,
Andrew

**Comment by Diviyan-Kalainathan** [comment]
Hi, 
Actually, the CGNN algorithm only searches in the graph space of the provided skeleton. I suppose that your skeleton is empty (not enough dependence between variables), that might come from the fact that you have only 10 values : the p-value associated with the dependence score is high, making the edge not retained. 
I order to have more consistent results, I would suggest using datasets of at least 100 samples.
And using the pairwise algorithms for datasets of 2 variables. 

Best,
 Diviyan

**Comment by andrewczgithub** [comment]
Thank you @Diviyan-Kalainathan !!
Much appreciated
