### ISSUE TITLE
[enhancement] Causal Estimation Code?

### ISSUE THREAD

**Issue by dcompgriff** [Diviyan-Kalainathan/CausalDiscoveryToolbox#59]
Hey. Maybe this is a dumb question, but has any thought been put into performing causal estimation in a graph in this package? It's great to have a package like this that does causal discovery, but I'd also like to have the functionality that can generate the conditional probability estimates over the causal graph, as well as a method for generating answers to Pr(Y|do(X=x)) for x and y being continuous and discrete. I've found the ability to do this kind of general calculation to be absent from most python packages. I currently use the pomegranate package to build a causal bayes net for my discrete variables (and I discretize continuous variables when I have them), and then use another package to determine backdoor or frontdoor based variables I can condition on, and then use the adjustment formula. It just all seems to be glued together however because all of this doesn't exist in the same package, especially for graphs with all discrete variables, which I would think is a simpler case than the continuous case.

 I know that 'DoWhy' exists, but it only allows for estimation of cause and effect for the direct effect case, where a treatment variable directly impacts an outcome variable.

**Comment by Diviyan-Kalainathan** [comment]
Hello,
Thanks for your interest ! The causal estimation module is planned to be integrated as it is not implemented for now ; however it might not be the priorities at the moment... I will look into it!
