### ISSUE TITLE
CGNN

### ISSUE THREAD

**Issue by firmai** [Diviyan-Kalainathan/CausalDiscoveryToolbox#6]
Hey man, thanks for this, looking forward to exploring. Just a quick question regarding and error, do you know what is causing this. 

![image](https://user-images.githubusercontent.com/26666267/39647780-5dcfcd6e-5034-11e8-9be4-265aa0b0766e.png)

**Comment by Diviyan-Kalainathan** [comment]
Hi,
Yes, the thing is that we haven't (still) updated the notebook since '0.2' , sorry ! 
I'll try to fix this notebook as soon as possible ! 
Best,

**Comment by Diviyan-Kalainathan** [comment]
Hi again,
Sorry for the delay, it should be working great now ! 
Best,
Diviyan

**Comment by firmai** [comment]
Thanks Diviyan, looking forward to playing around.
________________________________
