### ISSUE TITLE
Mini-batch train

### ISSUE THREAD

**Issue by thongnnguyen** [Diviyan-Kalainathan/CausalDiscoveryToolbox#9]
Hi,

I would like suggest to implement mini-batch training. Specifically, I tried to run `FSGNN` on my data and got the following error

```
not enough memory: you tried to allocate 160465GB. Buy new RAM! at /opt/conda/conda-bld/pytorch_1524584710464/work/aten/src/TH/THGeneral.c:218
```

I looked into the code but unfortunately I'm not familiar with GAN to modify the code.

**Comment by Diviyan-Kalainathan** [comment]
Hi,

You're right, some of the algorithms have this functionality, others
haven't. I should look into this.
Best,
Diviyan

**Comment by Diviyan-Kalainathan** [comment]
I'm sorry that it took so long, but it should be done. It revealed itself to be trickier than expected. Now instead of feeding raw data as a numpy array or Tensor, you can feed torch.utils.data.Dataset types, with a custom loading function of elements that you write accordingly to your data.

**Comment by Diviyan-Kalainathan** [comment]
I will be closing this issue, as it should be solved. Don't hesitate to reopen it if the bug still persists in the latest version.
Best,
Diviyan
